<a href="https://colab.research.google.com/github/YJYDM/progate_sample/blob/master/%E4%BD%9C%E6%A5%AD%E7%94%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
print('Hello world!!')

Hello world!!


In [57]:
#from google.colab import drive
#drive.mount('/content/drive')

In [58]:
import numpy as np


|$n$||$x_{n}$||$t_{n}$|
|:---||:---||:---|
|1||20||60000|
|2||40||115000|
|3||60||155000|

In [59]:
x = np.array([20,40,50,60,70])
x

array([20, 40, 50, 60, 70])

In [60]:
type(x)

numpy.ndarray

In [61]:
t = np.array([60000,115000,130100,155000,179900])
t

array([ 60000, 115000, 130100, 155000, 179900])

In [62]:
x_mean = x.mean()
x_mean

48.0

In [63]:
t_mean = t.mean()
t_mean

128000.0

In [64]:
xc = x - x_mean

In [65]:
tc = t - t_mean

$$
w = \dfrac{\sum_{n=1}^{N}x_{n}t_{n}}{\sum_{n=1}^{N} x_{m}^{2}}
$$


In [66]:
xc * tc

array([1904000.,  104000.,    4200.,  324000., 1141800.])

In [67]:
(xc * tc).sum()

3478000.0

In [68]:
w = (xc * tc).sum() / (xc * xc).sum()
w

2350.0

$$
y_{c} = w x_{c}
$$
$$
y_{c} = w x_{c}
$$

In [69]:
x = 65
y = w * (x- x_mean) + t_mean
y

167950.0